language: python
python:
  - "3.6"
before_install:
  - openssl aes-256-cbc -K $encrypted_1d2ab8ba5030_key -iv $encrypted_1d2ab8ba5030_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
install:
  - pip install -r .requirements/production.txt
script:
  - python app/manage.py test members.tests
  - python app/manage.py test house.tests
  - python app/manage.py test reservation.tests