# Generated by Django 2.0.3 on 2018-04-04 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자 까지의 물건의 이름을 저장 합니다.', max_length=100, unique=True, verbose_name='편의 물품')),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자 까지의 시설의 이름을 저장 합니다.', max_length=100, unique=True, verbose_name='편의 시설')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('AP', '아파트'), ('HO', '주택'), ('OR', '원룸')], default='HO', help_text='숙소를 선택 하세요. (기본값은 주택)', max_length=2, verbose_name='숙소 타입')),
                ('name', models.CharField(help_text='숙소의 이름을 입력하세요. (100자)', max_length=100, verbose_name='숙소 이름')),
                ('description', models.TextField(blank=True, help_text='숙소를 설명 하세요. (blank/null 가능)', null=True, verbose_name='숙소 설명')),
                ('room', models.PositiveSmallIntegerField(default=1, help_text='방 수를 입력 하세요. (기본값은 1개)', verbose_name='방 수')),
                ('bed', models.PositiveSmallIntegerField(default=0, help_text='침대 수를 입력 하세요. (기본값은 0개)', verbose_name='침대 수')),
                ('bathroom', models.PositiveSmallIntegerField(default=1, help_text='욕실 수를 입력 하세요. (기본값은 1개)', verbose_name='욕실 수')),
                ('personnel', models.PositiveSmallIntegerField(default=1, help_text='숙박 인원 입력 하세요. (기본값은 1명)', verbose_name='숙박 인원')),
                ('minimum_check_in_duration', models.PositiveSmallIntegerField(default=1, help_text='체크인 할 수 있는 최소 기간을 입력 하세요. (기본값은 1)', verbose_name='최소 체크인 기간')),
                ('maximum_check_in_duration', models.PositiveSmallIntegerField(default=3, help_text='체크인 할 수 있는 최대 기간을 입력 하세요. (기본값은 3)', verbose_name='최대 체크인 기간')),
                ('start_day_for_break', models.DateField(blank=True, help_text='날짜로 입력 가능 합니다.', null=True, verbose_name='쉬는 시작 날짜')),
                ('end_day_for_break', models.DateField(blank=True, help_text='날짜로 입력 가능 합니다.', null=True, verbose_name='쉬는 마지막 날짜')),
                ('maximum_check_in_range', models.PositiveSmallIntegerField(default=90, help_text='오늘을 기준으로 체크인이 가능한 일 수 적어주세요 (기본값은 90)', verbose_name='가능한 Day값')),
                ('fee_for_day', models.PositiveSmallIntegerField(default=100000, help_text='하루 요금을 적어 주세요. 기본값(100,000)', verbose_name='하루 요금')),
                ('created_date', models.DateField(auto_now_add=True, help_text='날짜로 입력 가능 합니다.(기본값은 오늘)', verbose_name='등록일')),
                ('modified_date', models.DateField(auto_now=True, help_text='날짜로 입력 가능 합니다.(기본값은 오늘)', verbose_name='수정일')),
                ('amenities', models.ManyToManyField(blank=True, help_text='편의 물품의 종류를 선택하세요. (blank/null 가능)', related_name='houses_with_amenities', to='house.Amenities', verbose_name='편의 물품')),
                ('facilities', models.ManyToManyField(blank=True, help_text='편의 시설을 선택하세요. (blank/null 가능)', related_name='Nearby_facilities', to='house.Facilities', verbose_name='편의 시설')),
                ('guest', models.ManyToManyField(blank=True, help_text='편의 시설을 선택하세요. (blank/null 가능)', related_name='Nearby_facilities', to=settings.AUTH_USER_MODEL, verbose_name='편의 시설')),
                ('host', models.ForeignKey(help_text='숙소를 등록하는 판매자 입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='houses_with_host', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house', verbose_name='숙소 이미지')),
                ('house', models.ForeignKey(help_text='이미지와 연결된 숙소를 저장합니다.', on_delete=django.db.models.deletion.CASCADE, related_name='houses_with_image', to='house.House', verbose_name='숙소')),
            ],
        ),
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='주소지를 입력 하세요 (200자)', max_length=200, verbose_name='주소지')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationWithHouseAndGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(help_text='게스트가 예약한 숙소 입니다.', on_delete=django.db.models.deletion.CASCADE, to='house.House', verbose_name='숙소')),
                ('user', models.ForeignKey(help_text='숙소를 예약한 게스트 입니다.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게스트')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='relationwithhouseandguest',
            unique_together={('house', 'user')},
        ),
    ]
