# Generated by Django 2.0.3 on 2018-04-04 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationwithhouseandguest',
            name='user',
            field=models.ForeignKey(help_text='숙소를 예약한 게스트 입니다.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게스트'),
        ),
        migrations.AddField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(help_text='이미지와 연결된 숙소를 저장합니다.', on_delete=django.db.models.deletion.CASCADE, related_name='house_images', to='house.House', verbose_name='숙소'),
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='편의 물품의 종류를 선택하세요. (blank/null 가능)', related_name='houses_with_amenities', to='house.Amenities', verbose_name='편의 물품'),
        ),
        migrations.AddField(
            model_name='house',
            name='facilities',
            field=models.ManyToManyField(blank=True, help_text='편의 시설을 선택하세요. (blank/null 가능)', related_name='houses_with_facilities', to='house.Facilities', verbose_name='편의 시설'),
        ),
        migrations.AddField(
            model_name='house',
            name='guest',
            field=models.ManyToManyField(blank=True, help_text='숙소를 예약한 게스트', related_name='reserved_houses', through='house.RelationWithHouseAndGuest', to=settings.AUTH_USER_MODEL, verbose_name='게스트'),
        ),
        migrations.AddField(
            model_name='house',
            name='host',
            field=models.ForeignKey(help_text='숙소를 등록하는 판매자 입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='houses_with_host', to=settings.AUTH_USER_MODEL, verbose_name='판매자'),
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.OneToOneField(help_text='주소와(서울 특별시 관악구 신림동 790-2 희망빌라2 2차 201호) 위도/경도를 저장 합니다 ', on_delete=django.db.models.deletion.CASCADE, to='house.HouseLocation', verbose_name='위치'),
        ),
    ]
