# Generated by Django 2.0.3 on 2018-04-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': '편의 물품'},
        ),
        migrations.AlterModelOptions(
            name='facilities',
            options={'verbose_name_plural': '편의 시설'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name_plural': '숙소'},
        ),
        migrations.AlterModelOptions(
            name='houseimage',
            options={'verbose_name_plural': '숙소 이미지들'},
        ),
        migrations.AlterModelOptions(
            name='houselocation',
            options={'verbose_name_plural': '위치'},
        ),
        migrations.AlterModelOptions(
            name='relationwithhouseandguest',
            options={'verbose_name_plural': '숙소와 게스트'},
        ),
        migrations.AddField(
            model_name='houseimage',
            name='kind',
            field=models.CharField(choices=[('IN', 'inner'), ('OU', 'outer')], default='IN', help_text='숙소 안 이미지 인지 바깥 이미지 인지 저장', max_length=2, verbose_name='이미지 타입'),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(help_text='100자 까지의 물건의 이름을 저장 합니다.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='maximum_check_in_duration',
            field=models.PositiveSmallIntegerField(default=3, help_text='체크인 할 수 있는 최대 기간을 입력 하세요. (기본값은 3=3박4일)', verbose_name='최대 체크인 기간'),
        ),
        migrations.AlterField(
            model_name='house',
            name='maximum_check_in_range',
            field=models.PositiveSmallIntegerField(default=90, help_text='오늘을 기준으로 체크인이 가능한 일 수 적어주세요 (기본값은 90)', verbose_name='체크인 가능한 Day값'),
        ),
        migrations.AlterField(
            model_name='house',
            name='minimum_check_in_duration',
            field=models.PositiveSmallIntegerField(default=1, help_text='체크인 할 수 있는 최소 기간을 입력 하세요. (기본값은 1=1박2일)', verbose_name='최소 체크인 기간'),
        ),
    ]
