# Generated by Django 2.0.3 on 2018-04-23 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='host',
            field=models.ForeignKey(help_text='숙소를 등록하는 호스트입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='houses_with_host', to=settings.AUTH_USER_MODEL, verbose_name='호스트'),
        ),
        migrations.AddField(
            model_name='house',
            name='reserve_days',
            field=models.ManyToManyField(blank=True, help_text='이미 예약된 날입니다.', related_name='houses_with_reserve_day', to='house.HouseReserveDay', verbose_name='예약된 날'),
        ),
    ]
