# Generated by Django 2.0.3 on 2018-04-15 10:33

from django.db import migrations
import house.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img_cover_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to=house.models.dynamic_img_cover_thumbnail_path),
        ),
    ]
