# Generated by Django 2.0.3 on 2018-04-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20180405_1114'),
        ('house', '0002_auto_20180406_1252'),
    ]

    operations = [
    ]
