# Generated by Django 2.0.3 on 2018-04-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20180423_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housedisableday',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='housereserveday',
            options={'ordering': ['date']},
        ),
    ]
