# Generated by Django 2.0.3 on 2018-04-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='end_day_for_break',
        ),
        migrations.RemoveField(
            model_name='house',
            name='start_day_for_break',
        ),
    ]
