# Generated by Django 2.0.3 on 2018-04-15 11:35

from django.db import migrations, models
import house.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimage',
            name='kind',
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(help_text='숙소와 연결된 이미지를 저장합니다.', upload_to=house.models.dynamic_img_house_path, verbose_name='숙소 이미지'),
        ),
    ]
