# Generated by Django 2.0.3 on 2018-04-12 05:18

from django.db import migrations, models
import house.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img_cover',
            field=models.ImageField(blank=True, default='', upload_to=house.models.dynamic_img_cover_path),
        ),
    ]
