# Generated by Django 2.0.3 on 2018-04-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_merge_20180406_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, default='', help_text='숙소를 설명 하세요. (blank/null 가능)', verbose_name='숙소 설명'),
            preserve_default=False,
        ),
    ]
