# Generated by Django 2.0.3 on 2018-04-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20180409_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='maximum_check_in_range',
            field=models.PositiveSmallIntegerField(help_text='오늘을 기준으로 체크인이 가능한 달 수 적어주세요 (기본값은 3)', verbose_name='체크인 가능한 한계 시간'),
        ),
    ]
