# Generated by Django 2.0.3 on 2018-04-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20180409_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='name',
            field=models.CharField(help_text='100자 까지의 물건의 이름을 저장 합니다.', max_length=100, unique=True),
        ),
    ]
