# Generated by Django 2.0.3 on 2018-04-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20180415_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(help_text='이미지와 연결된 숙소를 저장합니다.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='house.House', verbose_name='숙소'),
        ),
    ]
