# Generated by Django 2.0.3 on 2018-04-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20180415_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address2',
        ),
    ]
