# Generated by Django 2.0.3 on 2018-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_remove_house_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(decimal_places=14, help_text='위도를 소수점(7자리) 입력 가능 (xx.1234567)', max_digits=17, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(decimal_places=14, help_text='경도를 소수점(7자리) 입력 가능 (xxx.1234567)', max_digits=17, verbose_name='경도'),
        ),
    ]
