# Generated by Django 2.0.3 on 2018-04-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20180417_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(decimal_places=14, help_text='위도를 소수점(7자리) 입력 가능 (xx.1234567)', max_digits=16, verbose_name='위도'),
        ),
    ]
