# Generated by Django 2.0.3 on 2018-04-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20180418_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(decimal_places=14, help_text='위도를 소수점(14자리) 입력 가능 (xx.12345678901234)', max_digits=16, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(decimal_places=14, help_text='경도를 소수점(14자리) 입력 가능 (xxx.12345678901234)', max_digits=17, verbose_name='경도'),
        ),
    ]
