# Generated by Django 2.0.3 on 2018-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20180418_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseReserveDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='쉬는날을 입력해 주세요', unique=True, verbose_name='쉬는날')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='reserve_days',
            field=models.ManyToManyField(blank=True, help_text='이미 예약된 날입니다.', related_name='houses_with_disable_day', to='house.HouseReserveDay', verbose_name='예약된 날'),
        ),
    ]
