# Generated by Django 2.0.3 on 2018-04-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20180419_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='reserve_days',
            field=models.ManyToManyField(blank=True, help_text='이미 예약된 날입니다.', related_name='houses_with_reserve_day', to='house.HouseReserveDay', verbose_name='예약된 날'),
        ),
    ]
