# Generated by Django 2.0.3 on 2018-04-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20180420_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereserveday',
            name='date',
            field=models.DateField(help_text='예약된 날 입니다.', unique=True, verbose_name='예약된 날'),
        ),
    ]
