# Generated by Django 2.0.3 on 2018-04-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bank_account',
        ),
    ]
