# Generated by Django 2.0.3 on 2018-04-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(),
        ),
    ]
