# Generated by Django 2.0.3 on 2018-04-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('FI', '예약종료됨'), ('ON', '현재숙박중'), ('AC', '예약수락됨'), ('DE', '예약거절됨'), ('CH', '예약취소됨(호스트)'), ('CG', '예약취소됨(게스트)'), ('RE', '예약요청됨')], default='RE', max_length=2),
        ),
    ]
