# Generated by Django 2.0.3 on 2018-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('FI', '숙박종료됨'), ('ON', '현재숙박중'), ('AC', '예약수락됨'), ('DE', '예약거절됨'), ('CH', '예약취소됨(호스트)'), ('CG', '예약취소됨(게스트)'), ('RC', '예약요청취소됨'), ('RE', '예약요청됨')], default='RE', max_length=2),
        ),
    ]
