# Generated by Django 2.0.3 on 2018-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20180414_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_current_state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
