# Generated by Django 2.0.3 on 2018-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_reservation_current_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_current_state',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('AC', '예약수락됨'), ('DE', '예약거절됨'), ('CH', '예약취소됨(호스트)'), ('CG', '예약취소됨(게스트)'), ('RC', '예약요청취소됨'), ('RE', '예약요청됨')], default='RE', max_length=2),
        ),
    ]
