# Generated by Django 2.0.3 on 2018-04-11 23:57

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimages',
            name='img_profile',
            field=models.ImageField(blank=True, default='', upload_to=members.models.dynamic_img_profile_path),
        ),
    ]
