# Generated by Django 2.0.3 on 2018-04-10 06:52

from django.db import migrations
import imagekit.models.fields
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimages',
            name='img_profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to=members.models.dynamic_img_profile_path),
        ),
    ]
