# Generated by Django 2.0.3 on 2018-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_facebook_user',
            field=models.BooleanField(default=False),
        ),
    ]
