# Generated by Django 2.0.3 on 2018-04-05 08:32

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, default='/Users/smallbee/fc-projects/13team-project/finn-project/app/static/img_profile_default.png', upload_to=members.models.dynamic_img_profile_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
