# Generated by Django 2.0.3 on 2018-04-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(default='/static/iu.jpg', upload_to='user'),
        ),
    ]
