# Generated by Django 2.0.3 on 2018-04-06 03:52

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180405_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('members.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, default='', upload_to=members.models.dynamic_img_profile_path),
        ),
    ]
