# Generated by Django 2.0.3 on 2018-04-12 11:09

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180412_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileimages',
            name='img_profile_225',
        ),
        migrations.RemoveField(
            model_name='userprofileimages',
            name='img_profile_28',
        ),
        migrations.AlterField(
            model_name='userprofileimages',
            name='img_profile',
            field=models.ImageField(blank=True, default='', upload_to=members.models.dynamic_img_profile_path),
        ),
    ]
