# Generated by Django 2.0.3 on 2018-04-14 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180414_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileimages',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofileimages',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='images', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
