# Generated by Django 2.0.3 on 2018-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180404_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('members.user',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('members.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
